### ISSUE TITLE
Views missing in checkin

### ISSUE THREAD

**Issue by weedkiller** [LiviuSosu/CareerTrack#65]
Hello, this is very nice, where are the Views for the web app

**Comment by LiviuSosu** [comment]
Hello,

I am glad that you like this repository.

The short anywer to your question: https://github.com/LiviuSosu/CareerTrack-FrontEnd. This repository (where you opened the issue, not the CareerTrack-FrontEnd) is actually an api. I need to update the .md file. However, I am happy with the architecture. On the SolutionItems folder you may find the CareerTrack.postman_collection.json if you want to play the api.

Still, I need to implement the logout - for that I need to use Redis (a distributed cache). Versioning of the api and localization are also on teh list but for a ... later version.

This repository: https://github.com/LiviuSosu/CareerTrack-FrontEnd is a lot "younger". I am just using react with redux but at the moment of wrinting this, the "architecture" needs to improve among with my knowledge :-) 

Please let me know if you have other questions, otherwise you may close the issue.

Best,
Liviu

**Comment by weedkiller** [comment]
Hello, a base for the views would be nice so we can model and expand.

**Comment by LiviuSosu** [comment]
The idea of an API is to not have views.
